version: '3'

services:
  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    ports: ["8123:8123"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker_related_config.xml:/etc/clickhouse-server/config.d/docker_related_config.xml:rw
      - ./config.xml:/etc/clickhouse-server/config.xml:rw
      - ./users.xml:/etc/clickhouse-server/users.xml:rw
      - /data/clickhouse/lib:/var/lib/clickhouse:rw
      # - /data/clickhouse/log:/var/log/clickhouse-server

