global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "node_down.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
    - targets: ['node-exporter:9100']
      labels:
        instance: node

  - job_name: 'cadvisor'
    scrape_interval: 59s
    static_configs:
    - targets: ['cadvisor:8080']
      labels:
        instance: cadvisor
